version: '3.7'
services:
    master:
        container_name: "master"
        image: postgres:14
        expose:
            - 5432
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data1:/var/lib/postgresql/data
    replica1:
        container_name: "replica1"
        image: postgres:14
        expose:
            - 5433
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data2:/var/lib/postgresql/data
    replica2:
        container_name: "replica2"
        image: postgres:14
        expose:
            - 5434
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data3:/var/lib/postgresql/data
volumes:
    postgres_data1:
        driver: local
    postgres_data2:
        driver: local
    postgres_data3:
        driver: local